# Generated by Django 3.1.7 on 2021-03-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTGCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=10)),
                ('mana_cost', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
            ],
        ),
    ]
